"use client"

import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { IconSearch, IconFilter, IconDownload } from "@tabler/icons-react"

const leads = [
    {
        id: "LEAD-001",
        name: "John Doe",
        email: "john.doe@example.com",
        phone: "+1 (555) 123-4567",
        status: "Interested",
        agent: "Sales Bot Alpha",
        createdAt: "2026-01-29 10:30 AM",
    },
    {
        id: "LEAD-002",
        name: "Jane Smith",
        email: "jane.s@example.com",
        phone: "+1 (555) 987-6543",
        status: "Follow Up",
        agent: "Support Agent Beta",
        createdAt: "2026-01-28 02:15 PM",
    },
    {
        id: "LEAD-003",
        name: "Robert Johnson",
        email: "rob.j@example.com",
        phone: "+1 (555) 456-7890",
        status: "Not Interested",
        agent: "Sales Bot Alpha",
        createdAt: "2026-01-28 09:00 AM",
    },
    {
        id: "LEAD-004",
        name: "Emily Davis",
        email: "emily.d@example.com",
        phone: "+1 (555) 234-5678",
        status: "New",
        agent: "Survey Bot Gamma",
        createdAt: "2026-01-27 04:45 PM",
    },
    {
        id: "LEAD-005",
        name: "Michael Wilson",
        email: "m.wilson@example.com",
        phone: "+1 (555) 876-5432",
        status: "Interested",
        agent: "Sales Bot Alpha",
        createdAt: "2026-01-27 11:20 AM",
    },
]

export default function LeadsPage() {
    return (
        <div className="flex flex-col h-full p-6 space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Leads</h1>
                    <p className="text-muted-foreground">Manage leads generated by your voice agents.</p>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" className="h-9 gap-2">
                        <IconDownload className="h-4 w-4" />
                        Export
                    </Button>
                </div>
            </div>

            <div className="flex items-center gap-4">
                <div className="relative flex-1 max-w-sm">
                    <IconSearch className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                    <Input
                        placeholder="Search leads..."
                        className="pl-9"
                    />
                </div>
                <Button variant="outline" size="sm" className="h-9 gap-2">
                    <IconFilter className="h-4 w-4" />
                    Filter
                </Button>
            </div>

            <div className="rounded-md border">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Name</TableHead>
                            <TableHead>Contact</TableHead>
                            <TableHead>Status</TableHead>
                            <TableHead>Agent</TableHead>
                            <TableHead>Created At</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {leads.map((lead) => (
                            <TableRow key={lead.id}>
                                <TableCell className="font-medium">{lead.name}</TableCell>
                                <TableCell>
                                    <div className="flex flex-col text-sm">
                                        <span>{lead.email}</span>
                                        <span className="text-muted-foreground text-xs">{lead.phone}</span>
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <StatusBadge status={lead.status} />
                                </TableCell>
                                <TableCell>{lead.agent}</TableCell>
                                <TableCell>{lead.createdAt}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </div>
        </div>
    )
}

function StatusBadge({ status }: { status: string }) {
    let variant: "default" | "secondary" | "destructive" | "outline" = "default"

    switch (status) {
        case "Interested":
            variant = "default" // or success if available, defaulting to primary
            break;
        case "Not Interested":
            variant = "destructive"
            break;
        case "Follow Up":
            variant = "secondary"
            break;
        case "New":
            variant = "outline"
            break;
        default:
            variant = "outline"
    }

    // Custom coloring since shadcn Badge variants are limited by default palette
    // We can use tailwind classes for more specific colors if needed
    let className = ""
    if (status === "Interested") className = "bg-green-500/15 text-green-700 dark:text-green-400 hover:bg-green-500/25 border-green-500/20"
    if (status === "Not Interested") className = "bg-red-500/15 text-red-700 dark:text-red-400 hover:bg-red-500/25 border-red-500/20"
    if (status === "Follow Up") className = "bg-orange-500/15 text-orange-700 dark:text-orange-400 hover:bg-orange-500/25 border-orange-500/20"
    if (status === "New") className = "bg-blue-500/15 text-blue-700 dark:text-blue-400 hover:bg-blue-500/25 border-blue-500/20"

    return (
        <Badge variant="outline" className={className}>
            {status}
        </Badge>
    )
}
